- name: nginx related operations
  hosts: "{{ targets | default('localhost')}}"
  gather_facts: no
  become: yes
  tasks:
    - name: create user
      user:
        name: webadmin
        state: present

    - name: install nginx
      yum:
        name: nginx
        state: present

    - name: change default index.html path
      replace:
        path: /etc/nginx/nginx.conf
        backup: true
        regexp: '/usr/share/nginx/html'    
        replace: '/var/www/html/'

    - name: create index.html
      copy:
        dest:  /var/www/html/index.html
        content: | 
          <h2> Welcome to Ansible Automation for DevOps.</h2>
          <h3> This is sample project where Websites can be Automated, Deployment of web pages is done. </h3>
        owner: webadmin
        group: webadmin
        mode: '0664'

    - name: start nginx
      service:
        name: nginx
        state: started
