- name: nginx related operations
  hosts: "{{ targets | default('localhost')}}"
  gather_facts: no
  become: yes
  tasks:

    - name: stop nginx
      service:
        name: nginx
        state: stopped      

    - name: uninstall nginx
      yum:
        name: nginx
        state: absent

    - name: remove index.html
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: delete user webadmin
      user:
        name: webadmin      
        state: absent
